### ISSUE TITLE
Is this supposed to work with remote branches?

### ISSUE THREAD

**Issue by danielo515** [huizhougit/githd#1]
Hello,

This tool looks like something I have been looking for a while. I only made it work on the insiders edition of VScode, but I'm not here because that. I want to know if it is possible to use this extension to diff relative git commits (like HEAD~1) or even to compare the current branch with its remote counterpart. Something like this

```bash
git fetch # get the remote, but do not integrate
git diff develop origin/develop
```

Thanks and regards

**Comment by huizhougit** [comment]
Sorry for the late response. The latest githd (v0.3.0) should be able to work with VScode 1.14. Please let me know if you find bug or have trouble about it.
In terms of relative diff, I will add the it as a new feature since people like it :)
