### ISSUE TITLE
FEATURE REQUEST: compare two commits

### ISSUE THREAD

**Issue by Kevin-Hamilton** [huizhougit/githd#10]
It would be nice to be able to select two different commits and get a list of changed files and then be able to select any of those files to see the diff of that file between those two commits.

If it would be easier or make more sense, it would be acceptable to be able to select a file and then select two commits and be able to see the diff of that file between those two commits.  

Or at a mimimum, I'd like to be able to view the diff of a file between any arbitrary commit and the current working file.

**Comment by Kevin-Hamilton** [comment]
Thanks, this helps. But what I was kind of hoping for was a way to do this without checking out an earlier commit. That way I could have my current working file, in which I'm developing and testing some new code or a code refactor, and at the same time have open this history comparison which I'm referencing for the code that I'm currently developing.

**Comment by JoelAzaria** [comment]
Searching for a way to do exactly what @Kevin-Hamilton described - diff a file in a commit vs the open, working file.  Would be a nice addition to your extension.  Please consider.

**Comment by ringcrl** [comment]
Can you release a package with the latest version? This feature is very useful

**Comment by JoelAzaria** [comment]
> Can you release a package with the latest version? This feature is very useful @huizhougit

Oh my!   Yes please!!

**Comment by huizhougit** [comment]
Implemented by #19
