### ISSUE TITLE
Use a custom activity view

### ISSUE THREAD

**Issue by Tadaboody** [huizhougit/githd#12]
The [April 2018 Update](https://code.visualstudio.com/updates/v1_23#_extension-authoring) introduced an API to create custom activity views and have them on the activity bar.  
I think the extension moving to such a view would make the extension easier to use and remove some of the clutter in the explorer view caused by this and other extensions.  

>## Blemish
>* _Cannot focus on the explorer view automatically after selecting the commit._. 

I haven't used the API myself, but I reckon it would have a solution to this, opening the GitHD activity view after selecting a commit

**Comment by huizhougit** [comment]
oh, thanks for the information! I will update it in the next release.

**Comment by huizhougit** [comment]
Enabled in 1.2.0
