### ISSUE TITLE
View Line History is not working

### ISSUE THREAD

**Issue by idanpa** [huizhougit/githd#14]
My setup is Windows machine, with "Git For Windows" installed.
Other options working perfectly, but when using "View Line History" I get no changes and a file with:

No History

Where can I find the output log?
Thanks.

**Comment by huizhougit** [comment]
Can you try if this command works for you?
`git log -L <line number>,<line number>:<file>`
For example
`git log -L 10,10:file.js`

**Comment by idanpa** [comment]
git log -L <line number>,<line number>:<file> works from command prompt.

**Comment by huizhougit** [comment]
It should be fixed in v1.2.1. Please help to verify.
