### ISSUE TITLE
[Feature Request] Options to configure "Ctrl + click" to follow link.

### ISSUE THREAD

**Issue by artisdom** [huizhougit/githd#2]
Add option to allow configuration of the keys to follow link in the "Git History" list.
Want to just click on the link to follow it, too lazy to press the Ctrl key.
Cheers.

**Comment by huizhougit** [comment]
I wanted to follow the link with a single click as well. But VSCode extension doesn't support it directly. Your request makes me think harder about it. Seems I got some ideas and will try it.

**Comment by huizhougit** [comment]
Implement single-click in v0.8.0

**Comment by artisdom** [comment]
Tested, it's working great. :+1:
