### ISSUE TITLE
diff file 没有任何显示 

### ISSUE THREAD

**Issue by zhuchen0310** [huizhougit/githd#20]
![image](https://user-images.githubusercontent.com/29256306/47484923-8cccc680-d86f-11e8-926b-63393460f87c.png)

**Comment by huizhougit** [comment]
Can you try below command to see what's the output?
`git show f76e362`
And can you also add below to the settings and see what's the diff result?
`"editor.renderWhitespace": "all"`

**Comment by zhuchen0310** [comment]
👍 设置 重启后 完美解决! 感谢 !

**Comment by huizhougit** [comment]
That's great.
