### ISSUE TITLE
Include commit message body

### ISSUE THREAD

**Issue by ralfstx** [huizhougit/githd#22]
Thanks for this extension, I love it! Clean and simple. But there's one little thing I'm missing:

In our team, we value [good commit messages](http://chris.beams.io/posts/git-commit/). When looking at a commit, I would like to read through the details. The "Commit Info" seems to be the place to look for details on a commit, however, it includes only the summary line, not the entire message.

Could you include the full commit message in the "Commit Info"?

**Comment by huizhougit** [comment]
Good suggestion. Thanks! Will add it.

**Comment by huizhougit** [comment]
It's in 2.1.0

**Comment by ralfstx** [comment]
Thank you so much for the quick resolution. I love it!
