### ISSUE TITLE
[Feature Request] clickable issue reference in commit message  (e.g., #1111)

### ISSUE THREAD

**Issue by coolzilj** [huizhougit/githd#23]
Clickable issue reference in commit message  (e.g., #1111) would be very helpful, just like the web UI of github.
 ![image](https://user-images.githubusercontent.com/1059327/48826486-5f5b3600-eda5-11e8-85bd-32d9bb38d839.png)

**Comment by huizhougit** [comment]
I think you are talking about the git repository whose remote is github specific. But githd is generic for all the git repositories. So it doesn't have the context which should reference to where.

**Comment by huizhougit** [comment]
It would be great if you could do it.
