### ISSUE TITLE
command 'githd.viewStashes' not found

### ISSUE THREAD

**Issue by danielo515** [huizhougit/githd#33]
Issue Type: <b>Bug</b>

I tried to list my staashes but I get the following error:

`command 'githd.viewStashes' not found`

Extension version: 2.1.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by huizhougit** [comment]
Cannot repro. Please make sure there is a git repo opened by vscode.
