### ISSUE TITLE
.git目录一定要在当前路径的根目录么？

### ISSUE THREAD

**Issue by ppggff** [huizhougit/githd#4]
请问.git目录一定要在当前的根目录么？

比如：/a/b/c/d.x
.git在c中
此时无法查看d.x的历史信息

**Comment by huizhougit** [comment]
目前git repository 必须是vscode 的根目录或上层目录。
一种workaround 是你可以同时把a 和 c 都加到同一个workspace。
我会在以后版本加入对git repository 是vscode中子目录的支持。

**Comment by huizhougit** [comment]
Supported in [v1.1.0](https://github.com/huizhougit/githd/blob/master/CHANGELOG.md#110)
