### ISSUE TITLE
How can i hide this icon

### ISSUE THREAD

**Issue by sungle3737** [huizhougit/githd#41]
![image](https://user-images.githubusercontent.com/27716524/74811236-6cfac500-5334-11ea-93d8-fd23980377b8.png)
### strange top bizarre blue green icon

i can't find in setting

**Comment by huizhougit** [comment]
Added this setting to 2.2.2.
![image](https://user-images.githubusercontent.com/4254119/74901142-c70c8200-5356-11ea-87ef-284dd69712a6.png)

**Comment by sungle3737** [comment]
![image](https://user-images.githubusercontent.com/27716524/74908735-0344ee80-53fa-11ea-99bd-b549a3020b6e.png)
IT still appear after restart

**Comment by huizhougit** [comment]
Try 2.2.3

**Comment by sungle3737** [comment]
very fast😁
