### ISSUE TITLE
无法正常显示和执行命令

### ISSUE THREAD

**Issue by tabooc** [huizhougit/githd#55]
![image](https://user-images.githubusercontent.com/1568167/116091349-4faf4c80-a6d7-11eb-8e7e-793aacf43aa1.png)

如上图，在有一台电脑上安装后没有展示扩展的图标，执行命令则一直加载中无法正常执行。

**Comment by beierzhijin** [comment]
same problem

**Comment by LinZiqing2020** [comment]
same problem
