### ISSUE TITLE
2.3.0-lastest cannot work

### ISSUE THREAD

**Issue by xiaocheng07** [huizhougit/githd#59]
回退到2.2.4才可以

**Comment by lbmdqq** [comment]
vscode zip版无法使用最新版  重新安装vscode 下载vscode安装版就可以正常使用

**Comment by nameisnotavsilable** [comment]
v2.3.4-lastest cannot work,as well

**Comment by huizhougit** [comment]
@nameisnotavsilable can you please share your environment and the githd logs?

**Comment by huizhougit** [comment]
Really sorry for the so late reply, It should be fixed in v2.3.7

**Comment by nameisnotavsilable** [comment]
没事儿，可以用了
