### ISSUE TITLE
在搜索框找不到githd选项

### ISSUE THREAD

**Issue by MissLlq** [huizhougit/githd#6]
周同志，你好，请教一下，我在vscode中安装了git history diff的扩展，为什么我按F1后输入githd总会提示没有匹配命令，我的电脑没有连外网，是因为网络的原因吗？

**Comment by huizhougit** [comment]
vscode 要打开有git repository 的 folder 才会有GitHD 相关的功能

**Comment by MissLlq** [comment]
整个项目就在git repository里面。还是没有

**Comment by huizhougit** [comment]
你能做以下操作，然后告诉我输出吗？能录个屏最好
1. press ctrl+` to open the terminal
2. git rev-parse --show-toplevel

**Comment by huizhougit** [comment]
@aimergenge can you open a windows cmd and run `where git`

**Comment by aimergenge** [comment]
@huizhougit cannot find the git
![image](https://user-images.githubusercontent.com/13799160/47974117-07ed7280-e0e3-11e8-8dde-f3ab56e9b583.png)
but in git bash, git can be found
![image](https://user-images.githubusercontent.com/13799160/47974127-1c316f80-e0e3-11e8-816e-2d40c13b841a.png)

**Comment by aimergenge** [comment]
I think you shoud get the path from 'git.path' of vscode settings, so users can custom their own git application.

**Comment by huizhougit** [comment]
The fix will be in the next release.
