### ISSUE TITLE
Git command line broken since 2.3.0

### ISSUE THREAD

**Issue by zakarum** [huizhougit/githd#61]
# Env
VScode Version: 1.71.2 (system setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

# Symptom
The extension doesn't work

# Suspected Cause
The git command line changed to full path since 2.3.0, it will be broken if the path contains blanks (e.g., spaces). The default install path of git Windows is `C:\Program Files\Git`, which makes this issue more common on Windows.

![image](https://user-images.githubusercontent.com/13358026/192106200-d5690ff2-acb2-4ef4-b7a1-910e75b0dafc.png)

# Workaround
Reinstall git to a path without blanks or make a soft link to the installed git, then change the VScode git path points to the new path. For example:
`"git.path": "C:\\Git\\bin\\git.exe"`

**Comment by huizhougit** [comment]
Really sorry for the so late reply, It should be fixed in v2.3.7
