### ISSUE TITLE
the issue about GitHD diff over Remote-SSH

### ISSUE THREAD

**Issue by shuzf** [huizhougit/githd#68]
I have been using the vscode in development proccess, vscode built-in git extension is too large to consume more cpu resource, so i choose to install GitHD which is smaller, but git commmited files diff feature is not working in remote-ssh mode, please checkout  and fix, thanks! 
Version informations as follow,
version： VSCode 1.74.3
GitHD:  v2.3.3

**Comment by huizhougit** [comment]
Really sorry for the so late reply, It should be fixed in v2.3.7
