### ISSUE TITLE
What's the meaning of 'Express On/Off' on the status bar?

### ISSUE THREAD

**Issue by Jancat** [huizhougit/githd#7]
I haven't seem it in instruction and have no idea how it works?
![image](https://user-images.githubusercontent.com/11827786/34861958-a4966a7c-f7a2-11e7-875e-75bcf37a6dd2.png)

**Comment by huizhougit** [comment]
The history will be loaded much faster if you turn on express mode. But the stats information will not be shown.
It is mentioned in the [Configuration](https://github.com/huizhougit/githd#configuration) but seems it is not conspicuous.

**Comment by Jancat** [comment]
what's the `stats information` means?

**Comment by huizhougit** [comment]
Something like

````Find git repo in the first level folder````
````2cfc0ea by Hui Zhou <zhou_hui@outlook.com>, Thu Dec 28 2017 (2 weeks ago)````
**````2 files changed, 10 insertions(+), 7 deletions(-)````**

**Comment by jackphilippi** [comment]
I came here to ask the same question. Might be worth noting in the README ?
