### ISSUE TITLE
 Git History Diff prompt “command 'githd.viewHistory' not found”

### ISSUE THREAD

**Issue by nielinxin** [huizhougit/githd#70]
I have a remote linux env, and I use VSCode remote-ssh plugin to connect to it. I also installed Git History Diff  in the remote linux. Tody this plug doesn't work fine, and the version is upgrade to v2.3.3. prompt“command 'githd.viewHistory' not found”

**Comment by huizhougit** [comment]
Really sorry for the so late reply, It should be fixed in v2.3.7
