### ISSUE TITLE
bugfix: After the Clear button is clicked, the view list is not refreshed.

### ISSUE THREAD

**Issue by 1684838553** [huizhougit/githd#75]
version: v2.3.3

In the githd-explorer view, click the clear button. The expected result is to clear the displayed list, but the expected response is not achieved.
In addition, click Clear, and then click Collapse All to clear the list.

![image](https://github.com/huizhougit/githd/assets/41181666/5e852759-7b2e-4b8a-a4b7-05d1fd3869ea)

The cause is that the list is not refreshed after you click Clear.
 Please check and fix the bug. Thank you!

**Comment by huizhougit** [comment]
Really sorry for the so late reply, It should be fixed in v2.3.7
