### ISSUE TITLE
GitHD: View File History not working with Git for Windows 2.44.0

### ISSUE THREAD

**Issue by jibbers42** [huizhougit/githd#78]
When choosing "GitHD: View File History" from the editor's right-click menu, a new tab is opened for the "Git History", but it is never populated (it just remains blank).

OS: Windows 11
VSCode: 1.86.2
Git: 2.44.0
Git History Diff: v2.3.3

I rebooted the machine which did not help. I had to revert to git 2.43.0 to get it to work again.

**Comment by Jendker** [comment]
Same issue on MacOS with git version 2.44.0.

**Comment by emil-mordarski** [comment]
Same here, any solutions? This is my favorite extension to do this.

**Comment by huizhougit** [comment]
Thanks for reporting it @jibbers42 @Jendker @emil-mordarski. It's fixed in v2.3.4
