### ISSUE TITLE
在比较试图中可以编辑文件吗？

### ISSUE THREAD

**Issue by johnzhy** [huizhougit/githd#8]
在工作分支和新的master分支比较时，我想接受某些更改，能不能在比较视图中直接修改文件内容。

**Comment by huizhougit** [comment]
GitHD查看的比较内容都是已经committed 的 history。所以是不能在比较中编辑的。试想，文件 f 在branch A 和 branch master 中不同，且 f 已经有unstaged change，即 local 的 f 和branch A 中的 f 已经不同。比较视图中看到的是branch A 中已经 committed 的 f 而不是 local 的 f，而你想编辑的其实是local 的 f。
你可以用 git cherry-pick -n SHA1 来拿的需要的更改
