### ISSUE TITLE
Does any chance choice hide the button on status bar

### ISSUE THREAD

**Issue by loaden** [huizhougit/githd#9]
For now there exist a button called 'githd: Express Off', it's seems like a temp switch.
But I don't like it. I wanna make it hide. 
Any option for that? thanks! This is a great extension I like it much.
P.S. Could you speak Chinese? I am bad talk with English.

**Comment by huizhougit** [comment]
I just come back from a long travel. Will consider adding a config option to allow hiding it.

**Comment by huizhougit** [comment]
It is configurable in v1.1.4
