### ISSUE TITLE
Git History Diff出现fatal: invalid object name 'V2.15.6-release..file'.

### ISSUE THREAD

**Issue by xiaolifeipiao** [huizhougit/githd#90]
Git History Diff出现fatal: invalid object name 'V2.15.6-release..file'.

**Comment by huizhougit** [comment]
Can you provide the repro steps? @xiaolifeipiao

**Comment by xiaolifeipiao** [comment]
> Can you provide the repro steps? @xiaolifeipiao

选择文件夹对比版本；
![Uploading 20241112140609.jpg…]()

**Comment by huizhougit** [comment]
@xiaolifeipiao thanks for reporting this. It's fixed in v2.5.4
